### PR TITLE
Implement a backpressure for BoundedStorageProvider

### PR DESCRIPTION
**Pull request by jonahnm**
I made this using ChatGPT, tested it and was like "holy shit it actually works" although I would recommend doing more testing, just to be sure.

### CODE REVIEW

**Review by aschey — CHANGES_REQUESTED** [review]
Thanks for taking a stab at this! It's a noble attempt, but it seems ChatGPT isn't aware that using a synchronous `Condvar` in a function that will be called in an asynchronous context isn't a good idea.

I haven't put too much thought into this yet, but my guess is that maybe we can add another method to the `StorageProvider` trait called `is_writable` that will return whether or not the underlying storage is prepared to accept new data. If it returns `false`, we can skip calling `write` and check again after `read` is called at least once. That should give us similar behavior without blocking the task.

**Comment by jonahnm** [comment]
> Thanks for taking a stab at this! It's a noble attempt, but it seems ChatGPT isn't aware that using a synchronous `Condvar` in a function that will be called in an asynchronous context isn't a good idea.
> 
> I haven't put too much thought into this yet, but my guess is that maybe we can add another method to the `StorageProvider` trait called `is_writable` that will return whether or not the underlying storage is prepared to accept new data. If it returns `false`, we can skip calling `write` and check again after `read` is called at least once. That should give us similar behavior without blocking the task.

Gotcha! I should be able to implement this now that I have a base laid out.

**Comment by aschey** [comment]
Oh, quick correction. That method should probably be added to the `StorageWriter` trait and it can have a default value of `true` (only specific providers will need to override this

```rust
pub trait StorageWriter: Write + Seek + Send + 'static {
    /// Returns whether or not the writer is prepared to accept new data.
    fn is_writeable(&self) -> bool {
        true
    }
}
```

**Comment by aschey** [comment]
Handled by #94, ended up being a bit more complex than I thought.

**Pull request closed without merging**
