### PR TITLE
refactor(download) + feat(permanent storage)

### PR DESCRIPTION
**Pull request by dvdsk**
This contains a start on permanent storage. It consists of a lot of refactorings in source.rs which prep that module for further work. I am not opening the PR to get the refactorings merged to prevent future merge conflicts.

As the permanent storage feature is not completed yet all the related code is kept behind the unstable-permanent-storage feature.

The refactorings:

    extract some fields to their own struct
    (downloaded, position_reachable and requested_position)
    extract handling bytes during download to its own function
    potentially controversial: remove a lot of tracing code in an attempt to help readability as these spread out the logic quite a bit (imho)
    merges prefetch and handle bytes code, this de-duplicates some of the control flow

### CODE REVIEW

**Comment by dvdsk** [comment]
btw, what exactly happened when merging the previous pr? (#14 ). Its not squashed nor merged normally right?

**Review by aschey — CHANGES_REQUESTED** [review]
> potentially controversial: remove a lot of tracing code in an attempt to help readability as these spread out the logic quite a bit (IMHO)

I'll give this a more thorough look soon, but I can address this now. I see where you're coming from, but every tracing log is very valuable for debugging the output when something goes wrong. I agree it's unfortunate to have to sprinkle extra lines everywhere, but the nature of this type of code means it's very prone to race conditions, and when something weird happens, it's very helpful to be able to trace the execution path as closely as possible.

**Comment by aschey** [comment]
> btw, what exactly happened when merging the previous pr? (#14 ). Its not squashed nor merged normally right?

I did a squash merge, that was probably it.

**Comment by dvdsk** [comment]
> I did a squash merge, that was probably it. If you want to squash your commits on this branch into a single commit that's fine too, but for purposes of keeping the changelog clean, it needs to be one commit into main per PR.

ahhh the squash lost the description then, I am used to the squash moving all the commit messages into the squashed commits description. Was that also needed to keep the automatically generated changelog clean?

**Comment by dvdsk** [comment]
> see where you're coming from, but every tracing log is very valuable for debugging the output when something goes wrong.

I understand, tomorrow I will have a look if I can reintroduce some of the traces by instrumenting the new member functions that appeared as a process extracting some fields to structs. The rest will just have to be re-added, padding the code again.

**Comment by dvdsk** [comment]
On a separate note, how would you feel about moving the prefetch logic to the source handle?  Its methods have become trivial as the waiting logic was extracted to the `RequestedPosition` class. I think it can now easily handle the additional logic.

**Comment by dvdsk** [comment]
I had another good lock at everything I need for my application. I came to the conclusion that it doesn't really align with what I think you goals and needs for `stream-download` are. There isn't a clean way to fit everything in without making big changes to what you have made, and that's unfair to you.

I am gonna build a custom solution that is far less generic and composable as `stream-download` and only serves my applications needs.

You should feel free to change, modify or drop this PR (I suggest dropping the half finished permanent storage stuff). I unfortunately can not afford to work on it further :(

I learned a lot about the problem space of streaming from reading and working with your code. Particularly the test suite was instructive. 

Thank you for your patience and thank you for making this work open source!

**Comment by aschey** [comment]
> I had another good lock at everything I need for my application. I came to the conclusion that it doesn't really align with what I think you goals and needs for `stream-download` are. There isn't a clean way to fit everything in without making big changes to what you have made, and that's unfair to you.
> 
> I am gonna build a custom solution that is far less generic and composable as `stream-download` and only serves my applications needs.
> 
> You should feel free to change, modify or drop this PR (I suggest dropping the half finished permanent storage stuff). I unfortunately can not afford to work on it further :(
> 
> I learned a lot about the problem space of streaming from reading and working with your code. Particularly the test suite was instructive.
> 
> Thank you for your patience and thank you for making this work open source!

That's fair. It seems your requirements are quite a bit more complex than the use cases I thought of when designing the API. In general, I'm not opposed to large refactors if it makes the API more flexible. If you think your application would be better suited to something less generic, then that's cool too. I'll give this PR a look and see if any of the refactorings make sense on their own. 

Thanks for your contributions! Feel free to copy any parts of the code here for your own solution if it helps, and feel free to drop a link if you do make your own. I'd be happy to mention it as an alternative solution in the README here and I'd be curious to see what you end up needing to add.

**Pull request closed without merging**
